[package]
name = "yew-app-bounce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bounce = "0.7.0"
web-sys = "0.3.64"
yew = { version = "0.20.0", features = ["csr"] }
